## 00 PyTorch Fundamentals

In [60]:
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


## scalar

In [61]:
# scalar
scalar = torch.tensor(1)
scalar

tensor(1)

In [62]:
scalar.ndim

0

In [63]:
scalar.item()

1

# vector

In [64]:
vector = torch.tensor([7, 1])
vector

tensor([7, 1])

In [65]:
vector.ndim

1

In [66]:
vector.shape

torch.Size([2])

# Matrix

In [67]:
maxtrix = torch.tensor([[7, 8],  [9, 10]])
maxtrix

tensor([[ 7,  8],
        [ 9, 10]])

In [68]:
maxtrix.ndim

2

In [69]:
maxtrix.shape

torch.Size([2, 2])

# Tensor

In [70]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                        [[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [71]:
tensor.ndim

3

In [72]:
tensor.shape

torch.Size([2, 3, 3])

In [73]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [74]:
tensor[1]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Random Tensors

In [75]:
torch.rand(2,3)

tensor([[0.1104, 0.0936, 0.4935],
        [0.4590, 0.2670, 0.0872]])

In [76]:
torch.rand(2,3,3)

tensor([[[0.4391, 0.5520, 0.2332],
         [0.8480, 0.1418, 0.7159],
         [0.5647, 0.9869, 0.9114]],

        [[0.0846, 0.4675, 0.2721],
         [0.0075, 0.6187, 0.9292],
         [0.7092, 0.2046, 0.8307]]])

In [77]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [78]:
tensor * 10

tensor([10, 20, 30])

In [79]:
tensor = tensor * 10

In [80]:
tensor

tensor([10, 20, 30])

In [81]:
tensor - 10

tensor([ 0, 10, 20])

In [82]:
tensor = torch.subtract(tensor,7)

In [83]:
tensor

tensor([ 3, 13, 23])

In [84]:
tensor.subtract(7)

tensor([-4,  6, 16])

In [85]:
tensor = torch.tensor([1,2,3])

torch.matmul(tensor, tensor)

tensor(14)

In [86]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [87]:
tensor1 = torch.tensor([[1,2,3], [4,5,6]])
tensor2 = torch.tensor([[1,2], [2,3], [4,5]])

tensor2

tensor([[1, 2],
        [2, 3],
        [4, 5]])

In [88]:
torch.matmul(tensor1 , tensor2)

tensor([[17, 23],
        [38, 53]])

In [89]:
tensor = torch.arange(0, 100, 10)

In [90]:
tensor.dtype

torch.int64

In [91]:
tensor = tensor.type(torch.float64)
tensor

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float64)

In [92]:
tensor.mean()

tensor(45., dtype=torch.float64)

In [93]:
tensor.max()

tensor(90., dtype=torch.float64)

In [94]:
tensor.sum()

tensor(450., dtype=torch.float64)

In [95]:
tensor.argmin()

tensor(0)

In [96]:
tensor.argmax()

tensor(9)

In [97]:
tensor[tensor.argmax()]

tensor(90., dtype=torch.float64)

In [98]:
tensor = torch.tensor([[[1,2,3], [1,2,3]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3]]])

In [99]:
print(tensor.shape)

torch.Size([1, 2, 3])


In [100]:
tensor.reshape(3,1,2)

tensor([[[1, 2]],

        [[3, 1]],

        [[2, 3]]])

In [101]:
tensor = tensor.permute(2,0, 1)

In [102]:
tensor

tensor([[[1, 1]],

        [[2, 2]],

        [[3, 3]]])

In [103]:
tensor = torch.arange(1., 10.)

In [104]:
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [105]:
x_reshaped = tensor.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [106]:
x_reshaped.dtype

torch.float32

In [107]:
x = torch.tensor([[[1,2,3], [1,2,3]]])
x

tensor([[[1, 2, 3],
         [1, 2, 3]]])

In [108]:
y = x.permute(2,0,1)

In [109]:
y

tensor([[[1, 1]],

        [[2, 2]],

        [[3, 3]]])

In [110]:
y[0,0, 0 ]= 2

In [111]:
x

tensor([[[2, 2, 3],
         [1, 2, 3]]])

In [112]:
x = torch.tensor([1, 2, 3, 4])
x.shape

torch.Size([4])

In [113]:
x = x.unsqueeze(0)
x.shape

torch.Size([1, 4])

In [114]:
x

tensor([[1, 2, 3, 4]])

In [119]:
x = torch.tensor([[[1,2,3], [1,2,3]]])
y = x.permute(2, 0, 1).clone()
y[0,0,1] = 100
x

tensor([[[1, 2, 3],
         [1, 2, 3]]])

In [120]:
y

tensor([[[  1, 100]],

        [[  2,   2]],

        [[  3,   3]]])

In [121]:
x = torch.arange(1, 10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [122]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [124]:
x[0, 0]

tensor([1, 2, 3])

In [126]:
x = torch.rand(2,3, device="cuda")

In [130]:
array = np.arange(1.0, 8.0, dtype=np.float32)

In [128]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [133]:
torch.from_numpy(array).type(torch.float16)

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16)

In [134]:
tensor = torch.ones(4,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [135]:
tensor.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [136]:
tensor[0, 0] = 2

In [137]:
tensor

tensor([[2., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [139]:
torch.rand(3,4)

tensor([[0.0786, 0.3634, 0.0586, 0.6488],
        [0.3149, 0.4002, 0.4685, 0.5093],
        [0.7019, 0.7267, 0.0135, 0.5465]])

In [155]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [149]:
torch.seed()

377001176012400

In [156]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [151]:
torch.seed()

377007356440900

In [157]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [158]:
torch.cuda.device_count()

1

In [159]:
tensor_on_gpu = tensor.to(device)

In [160]:
tensor_on_gpu

tensor([[2., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')